export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";