export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const MY_APPOINTMENTS_REQUEST = "MY_APPOINTMENTS_REQUEST";
export const MY_APPOINTMENTS_SUCCESS = "MY_APPOINTMENTS_SUCCESS";
export const MY_APPOINTMENTS_FAIL = "MY_APPOINTMENTS_FAIL";

export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";