export const ALL_EMPLOYEE_REQUEST="ALL_EMPLOYEE_REQUEST";
 export  const ALL_EMPLOYEE_SUCCESS="ALL_EMPLOYEE_SUCCESS";
export   const ALL_EMPLOYEE_FAIL="ALL_EMPLOYEE_FAIL";



export const EMPLOYEE_DETAILS_REQUEST="EMPLOYEE_DETAILS_REQUEST";
 export  const EMPLOYEE_DETAILS_SUCCESS="EMPLOYEE_DETAILS_SUCCESS";
export   const EMPLOYEE_DETAILS_FAIL="EMPLOYEE_DETAILS_FAIL";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";