export const ALL_EMPLOYEE_REQUEST="ALL_EMPLOYEE_REQUEST";
 export  const ALL_EMPLOYEE_SUCCESS="ALL_EMPLOYEE_SUCCESS";
export   const ALL_EMPLOYEE_FAIL="ALL_EMPLOYEE_FAIL";

export const ADMIN_EMPLOYEE_REQUEST = "ADMIN_EMPLOYEE_REQUEST";
export const ADMIN_EMPLOYEE_SUCCESS = "ADMIN_EMPLOYEE_SUCCESS";
export const ADMIN_EMPLOYEE_FAIL = "ADMIN_EMPLOYEE_FAIL";

export const NEW_EMPLOYEE_REQUEST = "NEW_EMPLOYEE_REQUEST";
export const NEW_EMPLOYEE_SUCCESS = "NEW_EMPLOYEE_SUCCESS";
export const NEW_EMPLOYEE_RESET = "NEW_EMPLOYEE_RESET";
export const NEW_EMPLOYEE_FAIL = "NEW_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_RESET = "UPDATE_EMPLOYEE_RESET";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";


export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_RESET = "DELETE_EMPLOYEE_RESET";
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL";



export const EMPLOYEE_DETAILS_REQUEST="EMPLOYEE_DETAILS_REQUEST";
 export  const EMPLOYEE_DETAILS_SUCCESS="EMPLOYEE_DETAILS_SUCCESS";
export   const EMPLOYEE_DETAILS_FAIL="EMPLOYEE_DETAILS_FAIL";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";


export const CLEAR_ERRORS="CLEAR_ERRORS";